# Generated by Django 2.2.7 on 2020-07-07 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('A', 'fundacja'), ('B', 'organizacja pozarządowa'), ('C', 'zbiórka lokalna'), ('D', 'domyślnie fundacja')], max_length=1)),
                ('categories', models.ManyToManyField(to='donations.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=5)),
                ('pick_up_date', models.DateTimeField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.TextField()),
                ('categories', models.ManyToManyField(to='donations.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Institution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
